config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:create, :new, :show, :index] do
  resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true,  inclusion: { in: %w(chinese italian japanese french belgian),
  message: "%{value} is not a valid category" }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true },  inclusion: { in: (0..5),
  message: "the number is not a between 0 and 5" }
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

    def index
      @restaurants = Restaurant.all
    end
  
    def show
        @restaurant = Restaurant.find(params[:id])
    end
  
    def new
      @restaurant = Restaurant.new
    end
    
    def create
      @restaurant = Restaurant.new(restaurant_params)
      @restaurant.save
      redirect_to restaurant_path(@restaurant)
    end

    
    private
  
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_restaurant, only: [:new, :create]
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end


  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>All restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>


<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number %>
  <%= f.number_field :phone_number %>
  <%= f.label :category %>
  <%= f.number_field :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<ul>
  <li>Address: <strong><%= @restaurant.address %></strong></li>
  <li>phone_number: <strong><%= @restaurant.phone_number %></strong></li>
  <li>category: <strong><%= @restaurant.category %></strong></li>
</ul>

<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %></li>
  <% end %>
</ul>


<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |t| %>
  <%= t.input :content %>
  <%= t.submit %>
<% end %>